apiVersion: app/v1
kind: Deployment
metadata:
  name: demo-nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: gchr.io/OWNER/demo-app:dev
        ports:
        - containerPort: 8080
