resources:
  - ../../base
  - ingress.yaml

namePrefix: dev-

labels:
  - pairs:
      env: dev

images:
  - name: nginx
    newName: ghcr.io/jasonvandeventer/demo-app
    newTag: latest

patches:
  - target:
      version: v1
      kind: Service
      name: demo-nginx
    path: service-port-patch.yaml
