resources:
  - ../../base
  - ingress.yaml

namePrefix: dev-

labels:
  - pairs:
      env: dev
    includeSelectors: true

images:
  - name: nginx
    newName: ghcr.io/jasonvandeventer/demo-app
    newTag: <TAG>

patches:
  - target:
      version: v1
      kind: Service
      name: demo-nginx
    path: service-port-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: demo-nginx
    path: container-port-patch.yaml
