name: build-and-deploy
on:
  push:
    paths:
      - "app/**"                    # build only when app changes
      - ".github/workflows/ci.yml"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  KUSTOMIZATION: gitops/apps/demo-nginx/overlays/dev/kustomization.yaml

jobs:
  build-push-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute vars
        id: vars
        run: |
          echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.OWNER_LC }}/demo-app:${{ steps.vars.outputs.TAG }}
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.OWNER_LC }}/demo-app:latest

      # Bump kustomization images[newName/newTag]
      - name: Update kustomization image/tag
        uses: mikefarah/yq@v4
        with:
          cmd: |
            yq -i '
              .images[0].newName = "ghcr.io/${{ steps.vars.outputs.OWNER_LC }}/demo-app" |
              .images[0].newTag  = "${{ steps.vars.outputs.TAG }}"
            ' "${{ env.KUSTOMIZATION }}"

      - name: Commit tag bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${KUSTOMIZATION}"
          git commit -m "ci: deploy demo-app ${{ steps.vars.outputs.TAG }} [skip ci]" || echo "No changes to commit"
          git push
